name: AI Review on PR diff

on:
  # コメントでトリガーする
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event.issue.pull_request && github.event.comment.body == '/ai-review' && contains(fromJson('["korosuke613", "defaultcf", "Kesin11", "r4mimu", "uta8a"]'), github.event.comment.user.login)
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable-ai-review.yaml
    secrets: inherit
    with:
      pr_number: ${{ github.event.issue.number }}
      user_id: ${{ github.event.comment.user.login }}
      environment: 'ai-review'
