name: AI Review on PR diff

on:
  # コメントでトリガーする
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event.issue.pull_request && github.event.comment.body == '/ai-review' && (github.event.comment.user.id == github.event.issue.user.id || github.event.comment.user.id == github.repository_owner)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Review PR diff with AI
        env:
          LOG_LEVEL: debug
          HEAD_REF: ${{ github.head_ref }}
        run: |
          deno run \
            --allow-env \
            --allow-run=git \
            --allow-write=./tools/dist \
            --allow-read=./articles \
            --allow-net=api.openai.com \
            ./tools/reviewDiffWithAi.ts \
            ${{ github.base_ref }} \
            ${{ env.HEAD_REF }}

      - name: Summarize AI Review log
        run: |
          {
            echo "# AI Review log"
            echo '```log'
            cat ./tools/dist/ai-review.log
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - uses: reviewdog/action-setup@v1

      - name: Comment on PR with ReviewDog
        run: |
          reviewdog -f=rdjson -reporter=github-pr-review -name=kiba-ai <./tools/dist/rdjson.json

      - name: Comment finish message on PR
        env:
          COMMENT_FILE: ${{ runner.temp }}/ai-review-finished.md
        run: |
          {
            echo "@${{ github.event.comment.user.id }} AI Review finished. Please check the review comments."
            echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            echo '```json'
            cat ./tools/dist/ai-usage.json
            echo '```'
          } >> "$COMMENT_FILE"
          gh pr comment ${{ github.event.issue.number }} --body-file "$COMMENT_FILE"
