name: CI for GitHub Actions

on: 
  pull_request:
    paths:
      - .github/workflows/*

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1

      - uses: actions/checkout@v3

      - uses: reviewdog/action-actionlint@v1
