name: CI for GitHub Actions

on: 
  pull_request:
    paths:
      - .github/workflows/*

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: corepack enable npm
      - run: npm ci
      - name: actionlint
        run: npm run lint:node-actionlint
