name: CI for Deno

on: 
  pull_request:
    paths:
      - .github/workflows/ci-deno.yaml
      - tools/**/*.ts
  push:
    # main ブランチで codecov へカバレッジを送るために push でもトリガーする
    paths:
      - .github/workflows/ci-deno.yaml
      - tools/**/*.ts
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check Deno scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check format
        run: |
          deno fmt --check ./tools
      
      - name: Check lint
        run: |
          deno lint ./tools

  test:
    name: Test Deno scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test
        run: |
          deno test --allow-run=git,grep --coverage=cov_profile tools/
          deno coverage cov_profile --lcov --output=cov_profile.lcov
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: deno-unittests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
