name: CI for Deno

on:
  pull_request:
    paths:
      - .github/workflows/ci-deno.yaml
      - tools/**/*.ts
  push:
    # main ブランチで codecov へカバレッジを送るために push でもトリガーする
    paths:
      - .github/workflows/ci-deno.yaml
      - tools/**/*.ts
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check Deno scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1 # v1.1.3
        with:
          deno-version: v1.x

      - name: Check format
        run: |
          deno fmt --ext=ts --check ./tools

      - name: Check lint
        run: |
          deno lint ./tools

  test:
    name: Test Deno scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1 # v1.1.3
        with:
          deno-version: v1.x

      - name: Test
        run: |
          deno test --allow-env=LOG_LEVEL --allow-read=tools --coverage=cov_profile tools/
          deno coverage cov_profile --lcov --output=cov_profile.lcov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@125fc84a9a348dbcf27191600683ec096ec9021c # v4.4.1
        with:
          flags: deno-unittests
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
