name: CI for npm

on: 
  pull_request:

jobs:
  check-run-zenn-cli:
    name: Check run zenn-cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: 'npm'

      - name: Install latest corepack
        run: |
          npm i -g corepack@latest

      - run: corepack enable npm

      - name: Install Dockerize
        env:
          DOCKERIZE_VERSION: v0.6.1
        run: |
          wget "https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz"
          tar -xzvf "dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz"
          rm "dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz"

      - run: npm ci

      - run: |
          npm run start &
          ./dockerize -wait http://localhost:8000  

      - run: curl http://localhost:8000
