name: Dry-run Renovate

on: 
  workflow_dispatch:
  pull_request:
    paths: 
      - .github/workflows/renovate-dry-run.yaml
      - renovate.json5

permissions:
  contents: read
      
jobs:
  renovate-dry-run:
    permissions:
      contents: read  # required by actions/checkout
      pull-requests: read  # required by renovate, because renovate to read pull request.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cybozu/renovate-dry-run-action@v1
        with:
          config-file: renovate.json5
          detail-summary: false
