name: Test AI Review on PR diff

on:
  # コメントでトリガーする
  workflow_dispatch:
    inputs:
      pr_number:
        required: true
        type: number
      user_id:
        required: true
        type: string

jobs:
  test-ai-review:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Test AI Review on PR diff"
